name: PRBuild
run-name: ${{ gitea.actor }} is building a docker image

on:
  pull_request:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Install Docker
        run: curl -fsSL https://get.docker.com | sh
      - name: Build
        run: docker build .